theme: jekyll-theme-minimal
title: Michał Podgórny
description: <b>Hi!</b> <p>I'm currently in my second year pursuing engineering degree in computer science at Wrocław University of Technology, Faculty of Fundamental Problems of Technology <a href="http://wppt.pwr.edu.pl/">(website)</a></p>
google_analytics: UA-136591401-1
