theme: jekyll-theme-minimal
title: Michał Podgórny
logo /me.jpg
description: <b>Hi!</b> I'm currently in my second year pursuing engineering degree in computer science at Wrocław University of Technology, Faculty of Fundamental Problems of Technology <a href="http://wppt.pwr.edu.pl/">(website)</a>
google_analytics: UA-136591401-1
