theme: jekyll-theme-minimal
title: Michał Podgórny
description: **Hi!** I'm currently in my second year pursuing engineering degree in computer science at Wrocław University of Technology, Faculty of Fundamental Problems of Technology [(website)](http://wppt.pwr.edu.pl/).
google_analytics: UA-136591401-1
