theme: jekyll-theme-minimal
title: Michał Podgórny
logo: https://doc-04-9s-docs.googleusercontent.com/docs/securesc/a3b8sg777b25gr35ne57lrc8b30i4jki/jtphp9j74oo9rtljpnm8p0pg14j778vk/1553040000000/06923609317604538620/06923609317604538620/1kgdctn-LwPNdoz1oW8A7WR1_WVOVeFw-?e=view
description: <b>Hi!</b> I'm currently in my second year pursuing engineering degree in computer science at Wrocław University of Technology, Faculty of Fundamental Problems of Technology <a href="http://wppt.pwr.edu.pl/">(website)</a>
google_analytics: UA-136591401-1
